apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-management-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-management
  template:
    metadata:
      labels:
        app: client-management
    spec:
      containers:
      - name: client-api
        image: your-dockerhub-username/chartered-accountant-webapp:${{ github.sha }}  # Specific tag
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri-secret  # Using a secret for sensitive info
              key: MONGO_URI
        livenessProbe:  # Health check
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:  # Readiness check
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: client-management-service
spec:
  type: ClusterIP  # Use LoadBalancer if external access is needed
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: client-management
